---
name: Linting jobs

# yamllint disable-line rule:truthy
on:
  - push
  - pull_request

jobs:
  lint-json:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Lint json
        uses: "docker://pipelinecomponents/jsonlint:latest"
        with:
          args: "find . -not -path './.git/*' -name '*.json' -type f -exec jsonlint --quiet {} ;"

