---
name: Linting jobs

# yamllint disable-line rule:truthy
on:
  - push
  - pull_request

jobs:
  php-linter:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: pipeline-components/php-linter@v0.12.6

